--Q1.What is the total revenue generated by male vs female customers?
SELECT gender, 
SUM(purchase_amount) AS total_revenue 
FROM customer 
GROUP BY gender; 
--Q.2 Which customers used a discount but still spent more than the average purchase amount?
SELECT*FROM customer
SELECT customer_id,
       purchase_amount 
FROM customer 
WHERE discount_applied = 'Yes' and purchase_amount>= (SELECT AVG(purchase_amount) FROM customer)
--Q.3 Which are the top 5 products with the highest average review rating? 
SELECT item_purchased, 
       ROUND(AVG(review rating::2),2)as "Average Product Rating" 
FROM customer 
GROUP BY item_purchased 
ORDER BY AVG (review_rating) desc limit 5;
--Q.4 Compare the avg purchase amount between Standard and Express Shipping 
SELECT shipping_type, 
       ROUND(AVG (purchase_amout),2) 
FROM customer 
WHERE shipping_type in ('Standard', 'Express') 
GROUP BY shipping_type 
--Q.5 Do subscribed customers spend more? Compare avg spend and total revenue between subscribers and non-subscribers 
SELECT subscription_status, 
       COUNT (customer_id) as total_customers, 
	   AVG (purchase_amount) as avg_spend, 
       ROUND(SUM(purchase_amount),2) as total_revenue 
FROM customer 
GROUP BY subscription_status 
ORDER BY total_revenue,
         avg_spend desc; 

--Q.6 Which 5 products have the highest percentage of purchases with discounts applied? 
SELECT item_purchased, 
       ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate 
FROM customer 
GROUP BY item_purchased
ORDER BY discount_rate desc
limit 5

--Q.7  Segment customers into New, Returning, and loyal based on their total number of 
--previous purchases and show the couint of each segment
WITH customer_type as
(
SELECT customer_id,
       previous_purchases,
CASE WHEN previous_purchases = 1 THEN 'New' 
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
          ELSE 'Loyal'
		  END AS customer_segment
FROM customer

)

SELECT  customer_segment,
        COUNT(*) AS "Number of customers"
FROM customer_type
GROUP BY customer_segment


--Q.8 What are the most top 3 purchased products within each category?
WITH item_counts as (
SELECT category,
       item_purchased,
COUNT(customer_id) as total_orders
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer
GROUP BY category, item_purchased
)





























